---
- name: Get swap state
  become: yes
  shell: swapon -v
  register: swap_state
  check_mode: false
  changed_when: false

- name: swap off
  become: yes
  shell: swapoff -a
  when: swap_state.stdout != ''


- name: swap check (/etc/fstab)
  become: yes
  shell: grep -v "\s*#" /etc/fstab | awk '{print $2}' | grep swap -c
  register: swap_state_in_fstab
  check_mode: false
  changed_when: false
  ignore_errors: true

- name: disable swap (/etc/fstab)
  become: yes
  replace:
    path: /etc/fstab
    regexp: ([^\s]+\s+swap\s+.*)
    replace: '# \1'
  when: swap_state_in_fstab == true
