all:
  vars:
    ansible_user: xxxxx
  children:
  
    k8s_controller:
      hosts:
        controller:
          ansible_host: controller
          
    k8s_worker:
      hosts:
        worker1:
          ansible_host: worker-1